# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "0b0db016368caccc890a5d012214510bf5e1db278cef55ed01d7b55772656be3"  # change this!
  limiter: true  # enable this when running the instance for a public usage on the internet
  image_proxy: true
  public_instance: true
redis:
  url: redis://redis:6379/0
